"""create comparisons table

Revision ID: 25a72be2b7f3
Revises: c702234b7afd
Create Date: 2024-12-27 22:17:11.118618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '25a72be2b7f3'
down_revision = 'c702234b7afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_runs_id', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_deployments_id', table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workflow_run_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('ant_version', sa.VARCHAR(), nullable=True),
    sa.Column('antnode_version', sa.VARCHAR(), nullable=True),
    sa.Column('antctl_version', sa.VARCHAR(), nullable=True),
    sa.Column('branch', sa.VARCHAR(), nullable=True),
    sa.Column('repo_owner', sa.VARCHAR(), nullable=True),
    sa.Column('chunk_size', sa.INTEGER(), nullable=True),
    sa.Column('antnode_features', sa.VARCHAR(), nullable=True),
    sa.Column('peer_cache_node_count', sa.INTEGER(), nullable=True),
    sa.Column('generic_node_count', sa.INTEGER(), nullable=False),
    sa.Column('private_node_count', sa.INTEGER(), nullable=True),
    sa.Column('downloader_count', sa.INTEGER(), nullable=True),
    sa.Column('uploader_count', sa.INTEGER(), nullable=True),
    sa.Column('peer_cache_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('generic_vm_count', sa.INTEGER(), nullable=False),
    sa.Column('private_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('uploader_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('peer_cache_node_vm_size', sa.VARCHAR(), nullable=True),
    sa.Column('generic_node_vm_size', sa.VARCHAR(), nullable=False),
    sa.Column('private_node_vm_size', sa.VARCHAR(), nullable=True),
    sa.Column('uploader_vm_size', sa.VARCHAR(), nullable=True),
    sa.Column('evm_network_type', sa.VARCHAR(), nullable=False),
    sa.Column('rewards_address', sa.VARCHAR(), nullable=False),
    sa.Column('max_log_files', sa.INTEGER(), nullable=True),
    sa.Column('max_archived_log_files', sa.INTEGER(), nullable=True),
    sa.Column('evm_data_payments_address', sa.VARCHAR(), nullable=True),
    sa.Column('evm_payment_token_address', sa.VARCHAR(), nullable=True),
    sa.Column('evm_rpc_url', sa.VARCHAR(), nullable=True),
    sa.Column('related_pr', sa.INTEGER(), nullable=True),
    sa.Column('network_id', sa.INTEGER(), nullable=True),
    sa.Column('triggered_at', sa.DATETIME(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployments_id', 'deployments', ['id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workflow_name', sa.VARCHAR(), nullable=False),
    sa.Column('branch_name', sa.VARCHAR(), nullable=False),
    sa.Column('network_name', sa.VARCHAR(), nullable=False),
    sa.Column('triggered_at', sa.DATETIME(), nullable=False),
    sa.Column('inputs', sqlite.JSON(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_id', 'workflow_runs', ['id'], unique=False)
    # ### end Alembic commands ### 