"""new tables for recording comparison results

Revision ID: 5d9d759da1f9
Revises: 7bd28de81abe
Create Date: 2025-05-30 00:24:29.416179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9d759da1f9'
down_revision = '7bd28de81abe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_download_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('env_name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('standard_successful', sa.Integer(), nullable=False),
    sa.Column('standard_errors', sa.Integer(), nullable=False),
    sa.Column('standard_avg_time', sa.String(), nullable=False),
    sa.Column('random_successful', sa.Integer(), nullable=False),
    sa.Column('random_errors', sa.Integer(), nullable=False),
    sa.Column('random_avg_time', sa.String(), nullable=False),
    sa.Column('perf_successful', sa.Integer(), nullable=False),
    sa.Column('perf_errors', sa.Integer(), nullable=False),
    sa.Column('perf_avg_time', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['base_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_download_results_id'), 'comparison_download_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_download_results_id'), table_name='comparison_download_results')
    op.drop_table('comparison_download_results')
    # ### end Alembic commands ### 