"""add upload_size column to client deploys

Revision ID: a0e4838030a2
Revises: b086bfe93563
Create Date: 2025-04-19 00:51:02.838143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e4838030a2'
down_revision = 'b086bfe93563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_deployments', sa.Column('upload_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_deployments', 'upload_size')
    # ### end Alembic commands ### 