"""create deployments table

Revision ID: c702234b7afd
Revises: ec5e36f1cfc7
Create Date: 2024-12-27 20:21:48.671175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c702234b7afd'
down_revision = 'ec5e36f1cfc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 