"""new upload error types

Revision ID: d14345e1e4ca
Revises: dd51b407c0ff
Create Date: 2025-06-13 22:02:59.303478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14345e1e4ca'
down_revision = 'dd51b407c0ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_upload_results', sa.Column('payment_error_count', sa.Integer(), nullable=True))
    op.add_column('comparison_upload_results', sa.Column('put_record_quorum_error_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison_upload_results', 'put_record_quorum_error_count')
    op.drop_column('comparison_upload_results', 'payment_error_count')
    # ### end Alembic commands ### 