"""new tables for recording comparison results

Revision ID: dd51b407c0ff
Revises: 5d9d759da1f9
Create Date: 2025-05-30 00:25:23.264186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd51b407c0ff'
down_revision = '5d9d759da1f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 