"""record the client and node environment variables for a deployment

Revision ID: e6e242f022a1
Revises: ccd080ec96e5
Create Date: 2025-03-04 22:50:13.718181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e242f022a1'
down_revision = 'ccd080ec96e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upscale_runs_id', table_name='upscale_runs')
    op.drop_table('upscale_runs')
    op.drop_index('ix_upscale_events_id', table_name='upscale_events')
    op.drop_table('upscale_events')
    op.add_column('deployments', sa.Column('client_env', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('node_env', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'node_env')
    op.drop_column('deployments', 'client_env')
    op.create_table('upscale_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('upscale_run_id', sa.INTEGER(), nullable=False),
    sa.Column('workflow_run_id', sa.INTEGER(), nullable=True),
    sa.Column('generic_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('peer_cache_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('symmetric_private_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('full_cone_private_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('generic_node_per_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('peer_cache_node_per_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('symmetric_private_node_per_vm_count', sa.INTEGER(), nullable=True),
    sa.Column('full_cone_private_node_per_vm_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['upscale_run_id'], ['upscale_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upscale_events_id', 'upscale_events', ['id'], unique=False)
    op.create_table('upscale_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deployment_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('start_uploaders_workflow_run_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['start_uploaders_workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upscale_runs_id', 'upscale_runs', ['id'], unique=False)
    # ### end Alembic commands ### 